# Generated by Django 4.0.1 on 2024-05-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2013',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2013',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2014',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2014',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2015',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2015',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2016',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2016',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2017',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2018',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2018',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2019',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2019',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2020',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2020',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2021',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2021',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2022',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2023',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2023',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2024',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2024',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2025',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2026',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2026',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2027',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2027',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2028',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2028',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2029',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2029',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatements2030',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('companies_id', models.IntegerField()),
                ('parametr_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=300)),
                ('data_source', models.IntegerField()),
                ('trust_level', models.IntegerField()),
            ],
            options={
                'db_table': 'company_financial_statements2030',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataOfCompanies',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('inn', models.CharField(db_column='INN', max_length=64)),
                ('ogrn', models.CharField(db_column='OGRN', max_length=64)),
            ],
            options={
                'db_table': 'data_of_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametrs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'parametrs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'type_of_activity',
                'managed': False,
            },
        ),
    ]
